language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

script:
  - python setup.py install
  - pip install -r test_requirements.txt
  - pep8 ondelta --ignore=E501
  - pyflakes ondelta
  - cd testproject && python manage.py test
