language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

script:
  - python setup.py install 
  - pip install -r test_requirements.txt
  - pep8 appname --ignore=E501
  - pyflakes appname
  - cd testproject && python manage.py test